services:

  composer_manager.filesystem:
    class: Drupal\composer_manager\Filesystem

  composer_manager.manager:
    class: Drupal\composer_manager\ComposerManager
    arguments: ['@config.factory', '@module_handler', '@composer_manager.filesystem']

  composer_manager.packages:
    class: Drupal\composer_manager\ComposerPackages
    arguments: ['@lock', '@module_handler', '@composer_manager.filesystem', '@composer_manager.manager']
